// Fetch types
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE';

export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS';
export const FETCH_MOVIE_DETAILS_FAILURE = 'FETCH_MOVIE_DETAILS_FAILURE';

// Filters types
export const TOGGLE_POPULARITY = 'TOGGLE_POPULARITY';
export const TOGGLE_RATING = 'TOGGLE_RATING';
export const CHANGE_GENRE_VALUE = 'CHANGE_GENRE_VALUE';
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const RESET_FILTERS = 'RESET_FILTERS';
export const FETCH_NOW_PLAYING_MOVIES = 'FETCH_NOW_PLAYING_MOVIES';

// Pagination types
export const SET_PAGE_COUNT = 'SET_PAGE_COUNT';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const RESET_PAGE_NUMBER = 'RESET_PAGE_NUMBER';
